# Generated by Django 6.0.5 on 2026-05-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izlozba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=64)),
                ('datumNaPocetok', models.DateField()),
                ('datumNaZavrsuvanje', models.DateField()),
                ('opis', models.TextField()),
                ('lokacija', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Umetnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=64)),
                ('prezime', models.CharField(max_length=64)),
                ('umetnickiStil', models.CharField(choices=[('impressionism', 'IMPRESSIONISM'), ('pop art', 'POP ART'), ('graffiti', 'GRAFFITI')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UmetnickoDelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=64)),
                ('datumNaSozdavanje', models.DateField()),
                ('slika', models.ImageField(upload_to='images/')),
                ('izlozba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umetnickodelo', to='apps.izlozba')),
                ('umetnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.umetnik')),
            ],
        ),
    ]
