# Generated by Django 6.0.5 on 2026-05-29 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('tourGuide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tourguide')),
            ],
        ),
    ]
