# Generated by Django 6.0.5 on 2026-05-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
