# Generated by Django 6.0.5 on 2026-05-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_cake_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='baker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='apps.baker'),
        ),
    ]
