# Generated by Django 6.0.5 on 2026-05-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=30)),
                ('linkedIn', models.URLField()),
                ('sales', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=64)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saleDate', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('reserved', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('agents', models.ManyToManyField(related_name='estates', to='apps.agent')),
                ('characteristics', models.ManyToManyField(blank=True, related_name='estates', to='apps.characteristic')),
            ],
        ),
    ]
